id: adding_alt_attribute
learningObjectives:
  - Implement accessibility improvements based on audit suggestions.
hints:
  - Find the alt attribute in the image element and add the word `banner` to it.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: Now let's fix another accessilibity issue.
          - text: As you can see in the lighthouse report we are missing an `alt` attribute in the logo.
          - text: The alt attribute is important for screen readers to read the content of the image.
          - text: :instruction[So, open a PR that adds the alt attribute to the banner with the description `anythink logo`.]

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "Thanks @${user.githubuser}, I'll review the changes right away!"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "Looking good ${user.firstName}! You're now able to merge the PR."
                    delay: 1300
            - actionId: github_pr_approve
              params:
                person: head-of-rd
                message: "Looking good @${user.githubuser}! You're now able to merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR.
                    delay: 2500
                  - text: As always, don't hesitate to **ask for my help** by admitting that you're :input[stuck]{text="I'm stuck!"} and I'm your only hope 👼
                    delay: 2500
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR. Remember, you can always ask for my help on Snack.
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  frontend:
    capabilities:
      - jest-puppeteer
    testFile: "alt.test.js"
