id: auditing_accessibility
learningObjectives:
  - Audit the website's accessibility using Lighthouse or axe.
hints:
  - For a Lighthouse audit, you can use Chrome DevTools or install the
    Lighthouse CLI.
  - To use axe, you can install the axe browser extension or use axe-core in
    your project's test suite.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that you've audited the website's accessability, let's look at
              the results.
          - text: It looks like there are some issues with the constrant of one element, can you tell me the CSS selector of the element?
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
