id: reassessing_accessibility
learningObjectives:
  - Reassess the website's accessibility after implementing changes.
hints:
  - Repeating the same accessibility audit earlier will help you evaluate the
    impact of your changes.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Great work! Now that the initial improvements are in place, let’s
              reevaluate our app to see the impact of your efforts.
          - text: Run another accessibility audit on the frontend using Lighthouse or axe.
              Compare the results with the initial audit, and share any
              noticeable improvements or lingering issues with us.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Fantastic job! You've made significant strides in enhancing Anythink's
                accessibility. This will have a profound impact on the
                experience of users with diverse needs. Keep up the great work,
                and always consider accessibility when working on frontend
                projects. Well done!
      - actionId: finish_step
